# Jekyll LOCAL config
title: Paris 26 Gigapixels - Unreleased  # title of the documentation
description: >- # Description of the docs. (>- means to ignore newlines until next param)
  Responsive interface of the projet Paris 26 Gigapixels
#permalink: /:path/:basename/:output_ext
#destination: ../marcelrent/public/proto-app # Build relative path destination. The destination directory e.g. /blog
# keep_files: [cache]
